services:
  - type: web
    name: pharmacyfinder-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Jwt__Issuer
        value: PharmacyFinder
      - key: Jwt__Audience
        value: PharmacyFinderUsers
      - key: Cors__AllowedOrigins
        sync: false
      - key: Storage__Provider
        value: Cloudinary
      - key: Storage__MaxFileSizeMb
        value: "10"
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
      - key: Cloudinary__Folder
        value: prescriptions
      - key: Tesseract__DataPath
        value: tessdata
      - key: Tesseract__Language
        value: eng
      - key: BootstrapAdmin__Email
        sync: false
      - key: BootstrapAdmin__Password
        sync: false
      - key: BootstrapAdmin__FullName
        sync: false
